model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  # ckpt_path: /opt/ml/DALLE-Couture/pretrained_models/vqgan.1024.model.ckpt
  params:
    embed_dim: 256
    # n_embed: 1024
    # n_embed: 16384 # codebook size: 16(f) x 1024(number of codebook entries |Z|)
    n_embed: 8192 # codebook size: 8(f) x 1024(number of codebook entries |Z|)
    # monitor: val/rec_loss
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1, 1, 2, 2, 4] # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [8] # f값. 4 x 2로 이미지를 쪼개거나 아니면 4 x 4로 쪼갤 수 있음.
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 15000 # 1.5 epoch is 15000 steps when batch size is 12. 성욱: 20000, 준홍: 10000, 영진: 15000, 연주: 10000
        disc_weight: 0.8 # 성욱, 준홍, 영진 0.8 / 연주 0.2
        codebook_weight: 1.0
    # lossconfig:
    #   target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
    #   params:
    #     disc_conditional: false
    #     disc_in_channels: 3
    #     disc_start: 0
    #     disc_weight: 0.75
    #     disc_num_layers: 2
    #     codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 12
    num_workers: 4
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: /opt/ml/taming-transformers/data/little_train.txt
        size: 256
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: /opt/ml/taming-transformers/data/little_train.txt
        size: 256
